batch_size: 128
epochs: 80
lr: 0.001

device: cuda:0
num_workers: 4
seed: 1234
use_wandb: False

data_dir: data

pretrained: False
pretrain_path: outputs/pretrain/pretrain.pt

# Evaluation
model_path: 